### PR TITLE
Configuring with plone/meta

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@thet I do a code cleanup and CI setup here. Maybe wait for this before releasing?

**Comment by thet** [comment]
Oh, too late!
Let's just do another release after the code cleanup :)

Btw: https://github.com/collective/collective.lineage/issues/66

**Comment by petschki** [comment]
No problem ... ;)

**Comment by thet** [comment]
@petschki btw. I'm not against breaking compatibility with Python 2 or Plone 5 if it makes sense and makes the code cleaner.
The Plone 5 compatible fix in the other PR was mainly because it was easy. And I have still some Plone 5 sites running.

**Comment by petschki** [comment]
Would you agree with dropping py27 support? Plone5.2/py38+ is still supported then ...

**Comment by thet** [comment]
Absolutely. That would also give us access to the newer Python 3 expressions.

**Pull request merged**
